name: Vary Git History

on:
  schedule:
    # Run every hour. The script's internal logic will decide if it's time to work.
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering of the 'run' command

jobs:
  scheduled-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0 # Fetch all history, essential for rewriting.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install git-filter-repo

      - name: Configure Git User for Workflow Runner
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"

      - name: Run Regular History Alteration
        id: alter_script
        # This is the key change: we now explicitly call the 'run' command.
        run: python vary_history.py run

      - name: Force Push Changes
        if: steps.alter_script.outcome == 'success'
        run: |
          echo "Pushing altered history to the remote repository..."
          git push --force-with-lease